version: '3'
volumes:
  vendor-store:
services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}_app
    build: ./docker/app
    volumes:
    - ../source:/var/www/html
    - vendor-store:/var/www/html/vendor
  nginx:
    image: nginx
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    ports:
    - 8082:80
    - 4432:443
    volumes:
    - ../source/public:/var/www/html/public
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./docker/nginx/localhost-key.pem:/etc/nginx/certs/server.key
    - ./docker/nginx/localhost.pem:/etc/nginx/certs/server.crt
    depends_on:
    - app
  db:
    image: mysql/mysql-server:8.0
    container_name: ${COMPOSE_PROJECT_NAME}_mysql8
    environment:
      MYSQL_ROOT_PASSWORD: Root@0000
      MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME}_portal
      MYSQL_USER: ${COMPOSE_PROJECT_NAME}
      MYSQL_PASSWORD: Password@0000
      TZ: Asia/Tokyo
    volumes:
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3302:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=${COMPOSE_PROJECT_NAME}
      - PMA_PASSWORD=Password@0000
      - MEMORY_LIMIT=128M
      - UPLOAD_LIMIT=64M
#      - PMA_ABSOLUTE_URI="https://localhost:4443/"
    ports:
      - 8083:80
#      - 4443:443
    depends_on:
      - db